# Generated by Django 6.0.2 on 2026-02-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
