# Generated by Django 5.1.7 on 2026-02-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_membershipplan_end_date_membershipplan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coverage_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='coverage_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
