# Generated by Django 5.1.7 on 2026-02-15 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV', max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1001)),
                ('padding', models.PositiveIntegerField(default=4)),
                ('gym', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='frontend.gym')),
            ],
        ),
    ]
