# Generated by Django 5.1.7 on 2026-02-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
