# Generated by Django 5.1.7 on 2026-02-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_member_security_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Branch'), ('multi', 'Multi Branch')], default='single', max_length=10, null=True),
        ),
    ]
