# Generated by Django 5.1.7 on 2026-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_gym_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
