# Generated by Django 5.1.7 on 2026-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_payment_created_by_payment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
